# Generated by Django 4.2.4 on 2023-08-07 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='programmer',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='programmer',
            name='fullname',
            field=models.CharField(max_length=100),
        ),
    ]
